terraform-ibm-modules/terraform-ibm-powervs-instance

README.md

usage updated
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR …

docs: rename variable in usage

---

README.md

add renovate badge to readme since repo is maintained by renovate
Run the CI pipeline when the PR is ready for review …

docs: add renovate badge to readme

---

main.tf
module-metadata.json
outputs.tf

Support null and empty values for storage variable
Run the CI pipeline when the PR is ready for review and you expect …

fix: support null and empty values for storage

---

modules/terraform_templates/linux/ansible_exec.sh.tftpl

remove community general and community sap_install collections
Run the CI pipeline when the PR is ready for review and …

fix: remove ansible galaxy collection sap

---

modules/pi_instance_init/templates/linux/configure_os.sh.tftpl
solutions/default/README.md
solutions/default/main.tf

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
If the CI pipeline doesn't run when you …

fix: updating ansible playbook version

---

modules/pi_instance_init/templates/linux/configure_os.sh.tftpl

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
If the CI pipeline doesn't run when you …

fix: updating ansible playbook version 1.1.1

---

modules/pi_instance_init/templates/linux/configure_os.sh.tftpl

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
If the CI pipeline doesn't run when you …

fix: upgraded ansible playbook to v1.1.2

---

.github/workflows/ci.yml
cra-config.yaml

move cra config to yaml file
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a …

ci: move cra config to yaml file

---

cra-config.yaml

Due to SCC api changes, some of the commented out values in the yaml are changing. To avoid having to maintain the changes in every repo, I'm updating the yaml to only included the required config (aka removing commented out code)
If the CI pipeline …

ci: cleanup cra-config.yaml

---

modules/pi_instance_init/templates/linux/configure_os.sh.tftpl

Update ansible ibm power linux sap version to 1.1.3 which fixes chrony
```
/run pipeline
```

fix: update ansible version to 1.1.3

---

examples/default/variables.tf
examples/single-instance/variables.tf
modules/pi_instance/variables.tf
variables.tf

Support Dal10 DC. Remove conditional checks for DC in other places
```
/run pipeline
```

fix: support dal10 dc

---

modules/pi_instance_init/templates/linux/configure_os.sh.tftpl
modules/pi_instance_init/templates/linux/services_init.sh.tftpl

Add condition to support OS registration in PER DC (dal10)
```
/run pipeline
```

fix: update os registration for PER dc

---

modules/pi_instance_init/templates/linux/services_init.sh.tftpl

added a check for the subscription log file for SLES and RHEL
```
/run pipeline
```

fix: added a check for the subscription log file for SLES and RHEL

---

.github/workflows/ci.yml
cra-config.yaml
cra-tf-validate-ignore-rules.json

enable cra scan for repo
```
/run pipeline
```

ci: enable cra scan

---

README.md
examples/default/README.md
examples/default/version.tf
module-metadata.json
modules/pi_instance/main.tf
tests/pr_test.go
version.tf

add lifecycle to ignore changes for instance and volumes
```
/run pipeline
```

fix: add lifecycle

---

.secrets.baseline
README.md

Change source usage in readme
```
/run pipeline
```

docs: source usage

---

README.md

docs: include tested images in description

---

locals.tf
modules/pi-instance-init-linux/main.tf
modules/pi-instance-init-linux/pi_configure_network_services.tf
modules/remote-exec-ansible/README.md
tests/pr_test.go

Prevent create_filesystems and configure_network_serivces resources to execute parallely
```
/run pipeline
```

fix: add depends_on for ansible roles

---

examples/default/README.md
examples/default/pi_workspace.tf
examples/default/provider.tf
examples/default/variables.tf
tests/common-go-assets/cloudinfo-region-power-prefs.yaml
tests/pr_test.go

add regions prefs.yaml file
```
/run pipeline
```

ci: add regions prefs.yaml file

---

.secrets.baseline
README.md

docs: update usage

---

modules/ansible/main.tf
modules/ansible/templates-ansible/linux-init/ansible_exec.sh.tftpl
modules/ansible/versions.tf

BREAKING CHANGE: ansible module reworked
```
/run pipeline
```

fix: ansible-host private key

---

modules/ansible/ansible_node_packages.sh

ansible role version 2.1.1 fixes the SLES init
```
/run pipeline
```

fix: ansible role version 2.1.1 fixes the SLES init

---

README.md
examples/basic/README.md
examples/basic/version.tf
examples/single-instance-linux/README.md
examples/single-instance-linux/version.tf
version.tf

Upgrade IBM provider  tf version to 1.67.1
```
/run pipeline
```

fix: upgrade ibm provider version

---

modules/ansible/ansible_node_packages.sh
modules/ansible/templates-ansible/linux-init/playbook-linux-init.yml.tftpl

feat: upgrade ibm.power_linux_sap roles

---

examples/basic/README.md
examples/basic/version.tf
examples/single-instance-linux/README.md
examples/single-instance-linux/version.tf

chore: update tf version

---

modules/ansible/ansible_node_packages.sh

fix: community general package version

---

modules/ansible/ansible_node_packages.sh

fix: remove collection dependencies

---

examples/basic/README.md
examples/basic/main.tf
examples/basic/provider.tf
examples/basic/variables.tf
examples/single-instance-linux/provider.tf
examples/single-instance-linux/variables.tf

chore: enable dal14 dc for examples

---

examples/basic/README.md
examples/basic/version.tf

chore: upgrade tf provider

---

modules/pi-instance/main.tf

Make terraform ignore changes in pi_user_data
```
/run pipeline
```

fix: lifecycle ignore changes in pi_user_data

---

README.md

chore(docs): update tested images

---

examples/basic/README.md
examples/basic/version.tf
examples/single-instance-linux/README.md
examples/single-instance-linux/version.tf

chore: upgrade provider version
